# Generated by Django 3.2.18 on 2023-10-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('date', models.DateField()),
                ('Total_amount', models.CharField(max_length=246, null=True)),
                ('amt', models.CharField(max_length=246)),
            ],
        ),
    ]
