# Generated by Django 3.2.18 on 2023-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_emod_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='emod',
            name='amt_taken',
            field=models.CharField(default='', max_length=246),
            preserve_default=False,
        ),
    ]
